---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dql-log
  namespace: dql-logger
spec:
  selector:
    matchLabels:
      app: dql-log
  replicas: 1
  template:
    metadata:
      labels:
        app: dql-log
    spec:
      containers:
        - name: dql-log
          image: alikingdom/dqlbootcamp:latest
