apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodejs-pino-logger
 namespace: dql-logger
 labels:
   app: nodejs-pino-logger
spec:
 selector:
  matchLabels:
   app: nodejs-pino-logger
 template:
  metadata:
   labels:
    app: nodejs-pino-logger
  spec:
   containers:
   - image: safiaregistry.azurecr.io/hackathon/node-pino-logger:latest
     name: nodejs-pino-logger
     imagePullPolicy: Always
     ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: nodejs-pino-logger-svc
    namespace: dql-logger
spec:
    ports:
    - name: “nodejs-pino-logger”
      targetPort: 3000
      port: 3000
      nodePort: 30253
      protocol: TCP
    selector:
       app: nodejs-pino-logger
    type: NodePort
