apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: easytrade
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: gcr.io/dynatrace-demoability/easytrade/db:0d8bdc7
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "yourStrong(!)Password"
        resources:
          requests:
            cpu: 300m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: easytrade
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - name: mssql
    port: 1433
    targetPort: 1433
