apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: easytrade
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: gcr.io/dynatrace-demoability/easytrade/manager:0d8bdc7
        ports:
        - containerPort: 80
        env:
        - name: MSSQL_CONNECTIONSTRING
          value: "Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password"
        resources:
          requests:
            cpu: 150m
            memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: easytrade
spec:
  type: ClusterIP
  selector:
    app: manager
  ports:
  - name: http
    port: 80
    targetPort: 80
