apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: easytravel
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-pluginservice
  name: easytravel-pluginservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytravel-pluginservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: easytravel-pluginservice
        app: easytravel-pluginservice
      annotations:
        support.contact: "demoability@dynatrace.com"
        support.channel: "#team-demoability"
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Dconfig.apmServerDefault=APM -Djava.security.egd=file:/dev/./urandom
        image: wmsegar/easytravel-pluginservice:latest
        imagePullPolicy: "Always"
        name: easytravel-pluginservice
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /PluginService/ping
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
status: {}
