apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: easytravel
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-backend
  name: easytravel-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easytravel-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: easytravel-backend
        app: easytravel-backend
      annotations:
        support.contact: "demoability@dynatrace.com"
        support.channel: "#team-demoability"
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Dconfig.apmServerDefault=APM -Djava.security.egd=file:/dev/./urandom
        - name: ET_DATABASE_LOCATION
          value: easytravel-mongodb:27017
        - name: ET_PLUGIN_SERVICE_LOCATION
          value: easytravel-pluginservice:8080
        - name: ET_MONGO_AUTH_DB
          value: "admin"
        - name: ET_DATABASE_USER
          value: "etAdmin"
        - name: ET_DATABASE_PASSWORD
          value: "adminadmin"
        image: dynatrace/easytravel-backend
        imagePullPolicy: "Always"
        name: easytravel-backend
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /services/JourneyService/getLocations
            port: 8080
            scheme: HTTP
          periodSeconds: 60
          initialDelaySeconds: 240
          successThreshold: 1
          timeoutSeconds: 1  
      restartPolicy: Always
status: {}
