apiVersion: v1
kind: Service
metadata:
  namespace: easytravel
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-frontend
  name: easytravel-frontend
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  selector:
    io.kompose.service: easytravel-frontend
  type: LoadBalancer
